// <auto-generated />
namespace Tyler_Technologies_Solution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AllowManagerIdNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllowManagerIdNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202010150310128_AllowManagerIdNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
